---
title: pagetitle
projects:
- title: project1
  subtitle: subtitle1
  description: " working XXXXX The aim of this study is to design and build a 6 m diameter dome structure covered by a stretchable membrane; using the previously published work in Chebyshev Net gridshells [Baverel et al.], the introduction of singularity points in the grid design [Yannick Masson et al.]. A special case exists when introducing a single valence 3 singularity on the center of a spherical dome: the bracing of each patch follows the same direction as the rods of its neighbouring patches, leading to the assumption that structure and bracing could effectively be the same element. Regarding the design & construction of the membrane, some assumptions had to be made in order to simplify the welding process."
  author: project author2
  date: 2018
  location: barcelona
  area: 10sqm
  subject: fuck off2
  category: Case Study
  firm: "MPDA 18 – Vallés School of Architecture (ETSAV) – Universitat Politècnica de Catalunya (UPC)"
  supervisor: Enrique Soriano, Gerard Bertomeu
  big-images:
  - img/img_chania.jpg
  keywords: 
  - 1
  - 2
  - 3
  - 4
---

